config/routes.rb
Resizer::Application.routes.draw do
  get "main/index"

  resources :pictures do
    member do
      get 'crop'
    end
  end

  root :to => "main#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  has_attached_file :image,
    :path => ":rails_root/public/system/:class/:attachment/:id/:basename-:style.:extension",
    :url => "/system/:class/:attachment/:id/:basename-:style.:extension",
    :styles => {
      :small  => "100x100#",
      :medium => "300x300",
      :large  => "460x460",
      :util => "600x600",
      :desired => "700x700"
         },
    :processors => [:cropper]

  after_update :reprocess_image, :if => :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def image_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end

  private

  def reprocess_image
    image.reprocess!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    redirect_to pictures_path
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.find(:all, :order => 'image_updated_at desc')
  end

  def new
    @picture = Picture.new
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def create
    @picture = Picture.new(params[:picture])
    if @picture.save
      redirect_to crop_picture_path(@picture)
    end
  end

  def crop
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(params[:picture])
      flash[:success] = 'The picture was Successfully updated.'
      render :action => "crop"
    end
  end

  def destroy
    @picture = Picture.find(params[:id])

    if @picture.delete
      flash[:success]='The picture was successfully deleted.'
    end

    redirect_to pictures_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      =yield(:title)
    =stylesheet_link_tag :all, :recursive => true
    =javascript_include_tag :defaults
    =javascript_include_tag 'jquery.observe_field.js'
    =csrf_meta_tag
    =yield(:head)
  %body
    .container_16
      =render :partial => 'shared/header'
      =yield
      =render :partial => 'shared/footer'

app/views/main/index.html.haml
.grid_12.center
  %h2
    Image Resizer
.grid_4.center
  %h2
    Instructions
.clear
.grid_12
  &nbsp;
.grid_4
  %p
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
  %p
    Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
.grid_6
  File: 
  =@picture.image_file_name
.grid_6
  Size:
  =@picture.image_file_size

app/views/pictures/_crop_js.html.erb
<script>
  $(function() {
  $("#cropbox").Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0,0,0,0],
    aspectRatio: 1
  });

  $("#desired_w").observe_field(.5, function() {
    update_selector();
  });

  $("#desired_h").observe_field(.5, function() {
    update_selector();
  });

  });

  function update_crop(coords) {
    var ratio = <%= @picture.image_geometry(:original).width %> / <%=@picture.image_geometry(:util).width %>;
    $("#crop_x").val(Math.round(coords.x * ratio));
    $("#crop_y").val(Math.round(coords.y * ratio));
    $("#crop_w").val(Math.round(coords.w * ratio));
    $("#crop_h").val(Math.round(coords.h * ratio));
  };

  function update_selector() {
    var jcrop = $("#cropbox").data('Jcrop');
    var desired_w = $("#desired_w").val();
    var desired_h = $("#desired_h").val();
    var ratio = gcd(desired_w, desired_h);
    jcrop.setOptions({aspectRatio: (desired_w/ratio)/(desired_h/ratio)});
    jcrop.setSelect([0,0,$("#desired_w").val(), $("#desired_h").val()]);
  };

  function gcd(a, b) {
    return (b == 0) ? a : gcd (b, a%b);
  }
</script>

app/views/pictures/_form.html.haml
-form_for Picture.new, :html => {:multipart => true}  do |f|
  .grid_3.form-label
    =f.label :image, "Image"
  .grid_13.form-field
    =f.file_field :image
  .clear
  .grid_3.form-label
  =submit_tag "Upload Image"

app/views/pictures/_picture.html.haml
.grid_6
  =picture.image_file_name
  %br
  =link_to image_tag(picture.image.url(:small)), picture_path(picture)
.grid_3
  =number_to_human_size(picture.image_file_size)
.grid_3
  =picture.image_updated_at
.grid_3
  =link_to 'Crop', crop_picture_path(picture)
  |
  =link_to 'Delete', picture_path(picture), :method => 'delete'
.clear

app/views/pictures/crop.html.haml
-content_for :title do
  Crop Image
-content_for :head do
  =javascript_include_tag "jquery.Jcrop.min"
=render :partial => 'crop_js'
.grid_16
  %h2
    Step 1 - Upload and crop and image
.clear
.grid_16
  Choose an image from your system that you want to upload and work with.
=render :partial => 'form'

-form_for @picture do |f|
  .grid_16
    %h2 Step 2 - Specify Width and Height
    Enter the width and height of your desired image, to enable cropping.
    .form-field
      =f.label :desired_w, "Width"
      =f.text_field :desired_w, :size => 5, :id => "desired_w"
    .form-field
      =f.label :desired_h, "Height"
      =f.text_field :desired_h, :size => 5, :id => "desired_h"
  .clear
  .grid_16
    %h2
      Step 3 - Select the portion of the image you want to use
  .grid_2
    &nbsp;
  .grid_10
    =image_tag @picture.image.url(:util), :id => 'cropbox'

  .grid_4
    .caption.center
      Original
  .grid_4.center
    File Size:
    =number_to_human_size(@picture.image_file_size)
  .grid_4.center
    Dimensions:
    =Paperclip::Geometry.from_file(@picture.image.path(:original)).width
    x
    =Paperclip::Geometry.from_file(@picture.image.path(:original)).height
  .clear
  -for attribute in [:crop_x, :crop_y, :crop_w, :crop_h]
    .grid_4.center
      =f.hidden_field attribute, :id => attribute, :size => 5
  .grid_16
    %h2
      Step 4 -
      =submit_tag "Apply your changes"
      and view modified file
.clear
.grid_2
  &nbsp;
.grid_10.center
  .center
    Modified File
  =image_tag @picture.image.url(:medium), :id => "cropped"
.grid_4.caption.center
  Modified
.grid_4.center
  Modified File Size:
  =number_to_human_size(File.size(@picture.image.path(:desired)))
.grid_4.center
  Dimensions:
  =Paperclip::Geometry.from_file(@picture.image.path(:desired)).width
  x
  =Paperclip::Geometry.from_file(@picture.image.path(:desired)).height
.clear
.grid_16
  %h2
    Step 5 -
    =link_to "Save Modified file Locally", @picture.image.url(:desired)

app/views/pictures/edit.html.haml
.grid_16
  %h2
    Edit Picture
.clear
.grid_16.center
  =image_tag(@picture.image.url(:small))
=render :partial => 'form'

app/views/pictures/index.html.haml
.grid_13
  %h2
    Pictures
.grid_3
  =link_to 'Add and Crop a Picture', new_picture_path
.clear
.grid_6
  File Name
.grid_3
  File Size
.grid_3
  Updated At
.clear
=render :partial => 'picture', :collection => @pictures

app/views/pictures/new.html.haml
.grid_16
  %h2
    Step 1 - Upload a new image
.clear
.grid_16
  Choose an image from your system that you want to upload and work with.
=render :partial => 'form'

app/views/pictures/show.html.haml
.grid_16.center
  =link_to 'Return to ALL pictures', pictures_path
  |
  =link_to 'Crop', crop_picture_path(@picture)
.grid_2.center
  .caption Small
  =image_tag(@picture.image.url(:small))
.grid_6.center
  .caption Medium
  =image_tag(@picture.image.url(:medium))
.grid_8.center
  .caption Large
  =image_tag(@picture.image.url(:large))
.grid_16.center
  .caption Utility
  =image_tag(@picture.image.url(:util))
.grid_16.center
  .caption Original
  =image_tag(@picture.image.url(:original))
.grid_16.center
  .caption Desired
  =image_tag(@picture.image.url(:desired))

app/views/shared/_flash_display.html.haml
-unless flash.empty?
  .grid_16
    .flash_container
      %ul#flash
        -flash.keys.each do |k|
          %li{:class => k}
            =flash[k]
        -javascript_tag do
          setTimeout("new Effect.Fade('flash');", 3000)

app/views/shared/_footer.html.haml
.footer.grid_16
  Copyright &copy; 2011 - G5
    

app/views/shared/_header.html.haml
.header
  .grid_12
    #logo
      G5
  .grid_4.right
  .clear